### ISSUE TITLE
Chase Bank is providing QFX files with an element not supported in the DTD.

### ISSUE THREAD

**Issue by jralls** [libofx/libofx#1]
Full details, including a sample file, are in [GnuCash Bug 771451](https://bugzilla.gnome.org/show_bug.cgi?id=771451). The simplest work-around is to modify the DTD to accommodate the extra element, but that's obviously not desirable. Another more general workaround would be to make sanitize_proprietary_elements() more general so that it gets rid of any tags not in the DTD. Or it might be easier to pass an error handler to the OpenJade parser that simply ignores invalid flags.

**Comment by benoitg** [comment]
This was fixed in https://github.com/libofx/libofx/pull/18/commits/266f19747483d12b15058ae2d4823f6937c2778e , released in 0.9.13,  I don't know why we didn't close the issue before.
