### ISSUE TITLE
ofxconnect crashes with exit status 139

### ISSUE THREAD

**Issue by daissi** [libofx/libofx#12]
Hi,
I just forward here a bug opened on the Debian bug tracker by the Mayhem team some years ago [1]:

> ofxconnect crashes with exit status 139. We confirmed the crash by
> re-running it in a fresh debian unstable installation.
> 
> The attachment [1] contains a testcase (under ./crash) crashing the
> program. It ensures that you can easily reproduce the bug. Additionally,
> under ./crash_info/, we include more information about the crash such as
> a core dump, the dmesg generated by the crash, and its output.
> 
> Regards,
> The Mayhem Team (Alexandre Rebert, Thanassis Avgerinos, Sang Kil Cha, David Brumley, Manuel Egele)
> Cylab, Carnegie Mellon University
> 

Best,
Dylan

[1] https://bugs.debian.org/716625

**Comment by cstim** [comment]
Thanks. 

Again, I will happily add more contributors to this project, as I'm not interested much the maintainer job here anymore.
