### ISSUE TITLE
ofx2qif date parser does not account for daylight savings

### ISSUE THREAD

**Issue by lehresman** [libofx/libofx#14]
When I run ofx2qif with this file:

[example.qfx.zip](https://github.com/libofx/libofx/files/1760969/example.qfx.zip)

It prints the wrong date.  After some digging, I realized that it's because it is not properly applying daylight savings from my locale.

The date in the QFX file is 20170301, but it gets printed as "D28/2/2017".

Note that if I change the 20170301 in the QFX file to be 20170313 (which is the day after the US daylight savings time switch in 2017), the dates are parsed properly.

I suspect it is related to this:
https://github.com/libofx/libofx/blob/master/ofx2qif/ofx2qif.c#L58

I spent a few hours trying to fix it myself, but with no success.  My C skills are too rusty.

**Comment by benoitg** [comment]
That is very bizzare.  OFX date handling is a major mess (see:  https://raw.githubusercontent.com/libofx/libofx/master/lib/ofx_utilities.cpp, look for the string "DEVIATION FROM THE SPECS") but event with daylight savings time this shouldn't happen.

Your symptoms seem to indicate that our workaround is no longer working.    However, I do not see how daylight savings time can affect it.

**Comment by lehresman** [comment]
Yeah, I see what you mean.  This does seem similar, but somewhat unrelated.  Starting at 11:59 AM does seem like it should account for DST variation.  For what it's worth, this is happening on both Ubuntu 14.04.1 LTS, and macOS 10.13.1.  My timezone is US/Eastern.

**Comment by benoitg** [comment]
@lehresman When you run ofxdump on the same file, you have the same incorrect date, right?

**Comment by lehresman** [comment]
Yes.

```
ofx_proc_account():
    Account ID: 123456789  12345_0000123456-S0001
    Account name: Bank account 12345_0000123456-S0001
    Account type: CHECKING
    Currency: USD
    Bank ID: 123456789
    Account #: 12345_0000123456-S0001

ofx_proc_statement():
    Currency: USD
    Account ID: 123456789  12345_0000123456-S0001
    Start date of this statement: Wed Mar  1 11:59:00 2017 EST
    End date of this statement: Wed Mar  1 10:59:00 2017 EST

ofx_proc_transaction():
    Account ID : 123456789  12345_0000123456-S0001
    Transaction type: DEBIT: Generic debit
    Date posted: Tue Feb 28 23:00:00 2017 EST
    Total money amount: -48.00
    # of units: 48.00
    Unit price: 1.00
    Financial institution's ID for this transaction: 12345_0000123456-S0001|201703010001180681
    Name of payee or transaction description: Wal-Mart
    Extra transaction information (memo): DebitCard, Withdrawal, Processed
```

**Comment by lehresman** [comment]
I'm not sure if it's related, but interestingly I notice that "Start date of this statement" is 1 hour after "End date of this statement".

**Comment by benoitg** [comment]
@lehresman Any chance you can attach the file you used to generate this?  (It seems you already sanitized the account numbers)

**Comment by lehresman** [comment]
The only thing I changed was the account numbers.  Sorry, I can't send you the original since it contains sensitive data and a customer sent it to me in confidence.

**Comment by jralls** [comment]
@benoitg: It's a very [longstanding problem](https://sourceforge.net/p/libofx/bugs/39/) for which I submitted a patch 18 months ago.

**Comment by benoitg** [comment]
@jralls Well damn, that fell between the cracks when we moved from sourceforge.  Commited.  @lehresman can you compile it from source and confirm that it fixes it for you?

**Comment by benoitg** [comment]
Closing.  It works for me after the fix using the file provided by @lehresman
