### ISSUE TITLE
0.9.14 fails to recognize security identified only by CUSIP

### ISSUE THREAD

**Issue by ostroffjh** [libofx/libofx#21]
(I'm using libofx with KMyMoney)  I recently upgraded to libofx 0.9.14, and on importing OFX from Merrill Lynch, I get many 

> This imported statement contains investment transactions with no security.  These transactions will be ignored.

  The actual OFX includes (for example)
```
<SECID>
<UNIQUEID>G6095L109
<UNIQUEIDTYPE>CUSIP</SECID>
```
but the imported statement as shown by KMyMoney includes `security=""`

I've reverted to 0.9.13 and these transactions are now imported correctly.  I have examples of dividend and sell transactions which show this problem.  Please let me know if there is any additional information I can provide.

**Comment by benoitg** [comment]
@ostroffjh I need a full (sanitized) sample file.  

The difference between 0.9.14 and 0.9.13 is in the preparsing, information was sometimes dropped by the sanitization process.  If there are regressions in 0.9.14, they are likely to be from an indirect cause.

**Comment by ostroffjh** [comment]
@benoitg I should have known this was going to happen, but I can now generate the same error with 0.9.13, so I am now not sure if it is a regression, or perhaps something funny in my ofx files from Merrill Lynch.  I'll obviously have to do much more research before I confirm this an upload a sample ofx file.  (I'm always afraid that by trying to remove unneessary pieces of the ofx file to generate a smaller example, I'm actually removing something important.)

Am I correct that this message should not depend at all on information in the program using libofx?  Also, if I get the error importing from KMyMoney, should I expect to see anything related to that in the output from ofxdump for the same ofx input?

**Comment by benoitg** [comment]
@ostroffjh Actually, that error string isn't generated by libofx.  So your first step is to try ofxdump on the file, and check if any information is missing from it's output.

**Comment by ostroffjh** [comment]
@benoitg Thanks.  I've been trying to figure how to allocate the "blame" between libofx and KMyMoney.  My further testing is just making me more confused.  So far, I have not seen any complaints from ofxdump, but I haven't checked the output in sufficient detail.  I suppose I need to better understand exactly how KMyMoney calls libofx to parse the actual OFX, what gets returned, and how KMM uses that to create that intermediate file.  I probably won't post back here until I have something more definitive.

**Comment by ostroffjh** [comment]
Since I'm no longer able to reproduce this, I'm assuming it was a transient inconsistency between libofx, kmymoney, and maybe the phase of the moon.  I'm going to close this for now, and will reopen if it shows up again and I can produce a reasonably small test case.

**Comment by benoitg** [comment]
@ostroffjh Good luck!
