### ISSUE TITLE
Hang on comment over 2 lines disappeared

### ISSUE THREAD

**Issue by gbonnema** [libofx/libofx#25]
After a discussion on launchpad.net/homebank, I decided to post this bug report, even if it was solved with 0.9.14. I run Fedora 30 which has 0.9.13 at the moment. Using homebank (which relies on libofx for ofx parsing) I had several hangs due to a comment line that was divided on 2 lines. When asked to use ofxdump or ofx2qif, it turned out they had the same problem.

When I compiled 0.9.14 on my machine, it vanished even though I could not find the issue in the list of changes.

I post this, hoping to prevent it from reoccurring in future.

The example ofx files I have that show the problem, I have attached. `testfile-1.ofx` hangs on Fedora 30, while it does not when compiling 0.9.14. `testfile-2.ofx` does not hang. Only difference is the comment.
[testfiles.zip](https://github.com/libofx/libofx/files/3587700/testfiles.zip)

**Comment by benoitg** [comment]
It is very similar to https://bugs.gnucash.org/show_bug.cgi?id=797081, which involved libofx getting confused about the start and end positions of tags, ans was indeed was fixed in 0.9.14: https://github.com/libofx/libofx/commit/30388e2c2c839add0c09b2a075389b13d089d8f7
