### ISSUE TITLE
autogen.sh fails, missing README

### ISSUE THREAD

**Issue by skierpage** [libofx/libofx#26]
I cloned this project. I guessed I needed to run ./autogen.sh first, which created `INSTALL` but didn't create `./configure` that's the next step. Its last two lines of output are
```
Makefile.am: error: required file './README' not found
lib/Makefile.am: installing 'config/depcomp'
```
No big deal, obviously there's `README.md`. But I guess as a result of that error it doesn't create `configure`.

The workaround is to copy/symlink/touch `README` and re-run `autogen.sh`. Other projects have this bug, e.g. [Opendigitalradio](https://github.com/Opendigitalradio/qt-drmplus/issues/3) and [libusb](https://github.com/libusb/libusb/issues/296). The first link proposes a change to `config.ac` that avoids the issue..

**Comment by skierpage** [comment]
I now realize I caused this bug with my pull request #23 , sorry :-(

**Comment by cstim** [comment]
In b9cced6, thanks! Would you like to get write permissions to the project directly?

**Comment by rzr** [comment]
May the issue or lookup for README.md be supported by automake ? any link to this ?
