### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by skierpage** [libofx/libofx#27]
Thanks for commit 9c8acb69771dfe , without it Skrooge has the same problem reading Amex qfx files that [Gnucash had](https://bugs.gnucash.org/show_bug.cgi?id=797125). As I understand it, the Skrooge flatpak recipe `org.kde.skrooge.json` needs to refer to a libofx release URL newer than
```
   "type": "archive",
   "url": "https://github.com/libofx/libofx/archive/0.9.14.tar.gz",
   "sha256": "85a732efe3026e96fe1cf694ebdcf5d2c3b67adba85b9019abac44e7c43d8ce5"
```

**Comment by cstim** [comment]
Are you sure the current code in git is useful as another release? In particular, the build system IMHO is not working well, starting with the version number from configure.ac. Would you like to get write permissions yourself to fix this? Thanks!

**Comment by skierpage** [comment]
> Are you sure the current code in git is useful as another release? In particular, the build system IMHO is not working well, starting with the version number from configure.ac.

Yes, trying to build from latest git I saw the warning `configure.ac:68: warning: AC_INIT: not a literal: $LIBOFX_VERSION_RELEASE_STRING`. I saw a page somewhere referencing variable expansion as a known problem with autoconf init. Also, `./configure` gets `: error: OpenSP includes not found` so the build fails with `fatal error: ParserEventGeneratorKit.h: No such file or directory`,

> Would you like to get write permissions yourself to fix this?

I'm honored to think you think that I know how :smiley: . I'm just an early Skrooge tester tracking down bugs in it, sorry I can't be more help. Thanks for working on this library, release when you're ready.

**Comment by cstim** [comment]
Ok, I've fixed the build system, but eventually reverted the README.md renaming and renamed it back to README. Yes, doesn't render as nice on github, but at least it builds without too many annoying warnings. I call this a 0.9.15 release. I hope this is sufficient for you. All the best!
