### ISSUE TITLE
File format parameter not used in libofx_proc_file

### ISSUE THREAD

**Issue by miraks31** [libofx/libofx#29]
Hi,

The signature of libofx_proc_file is:
`int libofx_proc_file(LibofxContextPtr p_libofx_context, const char * p_filename, LibofxFileFormat p_file_type)`

But, whatever the value of p_file_type, the behavior is AUTODETECT because the same code is called: 
`libofx_context->setCurrentFileType(libofx_detect_file_type(p_filename));`

**Comment by cstim** [comment]
Your issue report was completely right, sorry for this weird error. Should be fixed now.
