### ISSUE TITLE
libofx_proc_file doesn't return an error if file format is not detected

### ISSUE THREAD

**Issue by miraks31** [libofx/libofx#30]
The last lines of libofx_proc_file are:

```
  switch (libofx_context->currentFileType())
  {
  case OFX:
    ofx_proc_file(libofx_context, p_filename);
    break;
  case OFC:
    ofx_proc_file(libofx_context, p_filename);
    break;
  default:
    message_out(ERROR, string("libofx_proc_file(): Detected file format not yet supported ou couldn't detect file format; aborting."));
  }
  return 0;
```

It means that, if the file format is not well detected, nothing is done and no error message returned (return 0).

Expected result: an error must be returned in the 'default' case.

**Comment by cstim** [comment]
Can you propose a code snippet that should be inserted there? Or a merge request? Also, I'm looking for other developers who would like to take over this library as maintainers. Thanks a lot!

**Comment by cstim** [comment]
Your report was completely right. The error value is now returned. Feel free to propose additional changes if you think the code needs further improvements.
