### ISSUE TITLE
Is the sourceforge project & website dead?

### ISSUE THREAD

**Issue by risicle** [libofx/libofx#31]
I notice that a new release has been made here which hasn't made it to sourceforge. A lot of e.g. distributions have the old website as this project's "home page" and it causes quite a bit of confusion if it continues to exist but be massively out of date. It makes it look like the whole project is abandoned. Should distributions be updating the "home page" of libofx to point to this github project?

**Comment by cstim** [comment]
I've uploaded the tarball there just now. The website isn't "massively" out of date as the release from February 2019 is also there, only the very last one was missing. Nevertheless I agree this is a bit unfortunate. Are you interested in joining as a developer here and making sure this is cleaned up well?

**Comment by risicle** [comment]
Sorry I don't have the time, I just wanted to resolve the ambiguity from a packager's point of view. Thanks for doing so.

**Comment by dpward** [comment]
Can we please reconfigure http://libofx.coeus.ca/ (and as a result, https://libofx.sourceforge.net) to simply redirect to this GitHub project?

Right now, most of the content there is outdated, and in fact many of the links don't function properly (the iframe is broken). Even if the links did work, they suggest that the libofx project currently uses CVS and mailing lists hosted by SourceForge. Unfortunately, someone could easily believe that this is in fact the current website (and wonder if the project is abandoned).

**Comment by cstim** [comment]
I've tried hard to clean up remaining old stuff from sourceforge. The project page there now contains also the note "This project has moved to github", and I've also removed the super-obsolete webpages and the `VHost libofx.coeus.ca`. Hopefully this should resolve this here.
