### ISSUE TITLE
If <MEMO> contains <BR/> the whole memo isn't imported

### ISSUE THREAD

**Issue by christopherlam** [libofx/libofx#32]
See https://bugs.gnucash.org/show_bug.cgi?id=797633 -- the Oz bank ING refuses to do things right(*), and e.g. inserts `<BR/>` in the middle of the MEMO field. In GnuCash it means the MEMO is not imported at all.

Is this a fixable issue?

(*) it also doesn't use the `<NAME>` field but rather concatenates into a long `<MEMO>` field which may include the BR tag such as `WALMART - EFTPOS Purchase with Cash Out - Receipt 17395 - Cash amount $10.00<BR/>Date 23 Feb 2020 Card XXXXX`. This is outside scope of this bug. But it means NAME-less and MEMO-less transactions are not very useful!

**Comment by christopherlam** [comment]
For posterity the offending OFX are repaired with:
https://github.com/goodvibes2/IngAusOfxFixWin/commit/1ff1a924ad94ea28d10c7a86fe6268b07b123d1d
https://github.com/goodvibes2/IngAusOfxFixWin/commit/b112ec2697334b8e4212196232b42efa824d6965

**Comment by cstim** [comment]
So the gnucash bugreport concludes that inserting a `<BR/>` is against the OFX spec anyway, i.e. the bank is sending a non-conforming file. And this ticket is a feature request that these `<BR/>` should be replaced in the `<MEMO>` tags into single spaces? But how do we activate such a special replacement only for those faulty files - is there a special marker that this is a file from this bank?

**Comment by cstim** [comment]
No more comment - closing this issue then. Feel free to reopen if new information can be added.

**Comment by christopherlam** [comment]
Just a note... Don't think there's a suitable marker for these files -- perhaps the feature request would be to sanitize inputs to accept (but `g_warn`) invalid input, replacing `<BR/>` with whitespace instead of discarding the memo completely. This applies to Description field as well.
