### ISSUE TITLE
Unable to import NEW qfx from American Express (AMEX)

### ISSUE THREAD

**Issue by Grogoyle** [libofx/libofx#33]
Reporting this from:
https://bugs.gnucash.org/show_bug.cgi?id=797125

Briefly: American Express has created a new download with more characters inside the <OFX> tag.
GnuCash uses libofx.  
libofx will not read the file with the "new" <OFX ...stuff...> tag.
The workaround is to remove the extra characters.

**Comment by wrobelda** [comment]
Not sure if related, but looks like ofxclient sorted it out by making the request harder more specific:
https://github.com/captin411/ofxclient/issues/72

**Comment by Grogoyle** [comment]
Update:  American Express export of QFX file and then import into GnuCash now works.  
The \<OFX\> tag is clean, so Amex seems to have fixed the problem with extra characters.
