### ISSUE TITLE
libofx_proc_buffer lacks implementation

### ISSUE THREAD

**Issue by jonasmalacofilho** [libofx/libofx#34]
While working on a Rust FFI for libofx, I noticed that trying to call `libofx_proc_buffer` results in an 'undefined reference' link error.

Taking a look at the source code, it seems that while the function is declared in `libofx.h`, it's not (yet) defined.

**Comment by cstim** [comment]
You are completely right. The function is nowhere implemented, so we need to remove them from the header.
