### ISSUE TITLE
Account number truncated

### ISSUE THREAD

**Issue by miraks31** [libofx/libofx#43]
Hi,

This issue has been detected through Skrooge with this bug: https://bugs.kde.org/show_bug.cgi?id=437727

**To reproduce it:**
1- Download and unzip the attached file
[437727.ofx.zip](https://github.com/libofx/libofx/files/6587269/437727.ofx.zip)
2- Launch the following command line:
ofxdump 437727.ofx 

**Result:**
LibOFX INFO: libofx_proc_file(): File format not specified, autodetecting...
LibOFX INFO: libofx_proc_file(): Detected file format: OFX (Open Financial eXchange (OFX or QFX))
LibOFX STATUS: find_dtd():DTD found: /usr/share/libofx7/libofx/dtd/opensp.dcl
LibOFX STATUS: find_dtd():DTD found: /usr/share/libofx7/libofx/dtd/ofx160.dtd
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SIGNONMSGSRSV1
(Above message occurred on Line 1, Column 6)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SONRS
(Above message occurred on Line 1, Column 22)
ofx_proc_status():
    Ofx entity this status is relevant to: SONRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate BANKMSGSRSV1
(Above message occurred on Line 3, Column 1)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate STMTTRNRS
(Above message occurred on Line 3, Column 15)
ofx_proc_status():
    Ofx entity this status is relevant to: STMTTRNRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

ofx_proc_account():
    Account ID: **null null **6e30799ffd6894455e45f1b**null**
    Account name: Bank account 6e30799ffd6894455e45f1bnull
    Currency: EUR
    Bank ID: null
    Branch ID: null
    Account #: 6e30799ffd6894455e45f1b

**Expected result:**
The account ID mustn't be truncated.
This must be the full value like in the ofx full:
<ACCTID>**6e30799ffd6894455e45f1bc6115cb57bdcd74481263c361c074137ce180fcc7**

**Comment by jralls** [comment]
Sorry, no. ACCTID has a max length of 22 characters per the OFX specifications, DTDs, and Schemas, including the latest version 2.3.

**Comment by cstim** [comment]
In other words: no, the request won't be implemented, because 22 character maximum length is what is specified.
