### ISSUE TITLE
Error in absense of line feeds

### ISSUE THREAD

**Issue by ghost** [libofx/libofx#5]
If an `ofx` file is missing line feeds after preamble tags, parsing seems to fail.

See here: https://bugs.launchpad.net/homebank/+bug/1664012/comments/2

**Comment by benoitg** [comment]
As far as I can tell, this is indeed a Homebank problem, not a libofx one.  Admiteddly our file header handling code is a mess, but in your case it does seem to parse the file properly.

**Comment by mdoyen** [comment]
Hi,

@benoitg: you can close this bug (which is not related to libofx), my mistake reading ticket sometime too quicky ! I will fix this into HB, it is well related to the way I detect the filetype.
sorry for annoyance anyway.

Maxime.
