### ISSUE TITLE
"cannot convert argument 2 from 'char **' to 'const char **'" under MSVC

### ISSUE THREAD

**Issue by wrobelda** [libofx/libofx#51]
Under MSVC, https://github.com/libofx/libofx/commit/9023c0f8b7744baebb28e2ff9b9e6e54ed0a4d33 causes MSVC to fail with:

```
 error C2664: 'size_t iconv(iconv_t,const char **,size_t *,char **,size_t *)': cannot convert argument 2 from 'char **' to 'const char **'
```

This isn't an issue under vcpkg, though, likely due to some leniency stemming from a particular set of compiler switches.

**Comment by jralls** [comment]
Or maybe the vcpkg build has a standard-compliant implementation of `iconv` that doesn't take the [problematic](https://stackoverflow.com/questions/2220916/why-isnt-it-legal-to-convert-pointer-to-pointer-to-non-const-to-a-pointer-to) `const char**` argument.

**Comment by cstim** [comment]
So should we revert 9023c0f ? Or what is the proposal on how to proceed?

**Comment by jralls** [comment]
How about
```
          int iconv_retval = iconv (conversion_descriptor,
                                      &inchar, &inbytesleft,
#ifdef WIN32 //Win32's iconv implementation takes a const char** inchar
                                      &inchar, &inbytesleft,
#else
                                      const_cast<char**>(&inchar), &inbytesleft,
#endif
                                      &outchar, &outbytesleft);
