### ISSUE TITLE
PR44 breaks the build with gengetopt older than 2.23.

### ISSUE THREAD

**Issue by jralls** [libofx/libofx#52]
```
gengetopt --unnamed-opts < /Users/john/Development/gtk-sources/libofx/ofxdump/cmdline.ggo
gengetopt: unrecognized option '--unnamed-opts'
Run gengetopt --help to see the list of options.
```

Because while `--unamed-opts` might not be correct according to the dictionary it's how the `gengetopt` option is spelled. ***Edit*** before gengetopt-2.23. gengetopt-2.23 accepts either spelling.

**Comment by cstim** [comment]
So I better revert the option renaming? No need to win a trophy for correct spelling, if that comes with the prize of breaking older versions?

**Comment by cstim** [comment]
Ok, I reverted the option renaming.

And the other spelling change was even more wrong in that commit.
