### ISSUE TITLE
Build broken on Linux with gcc 5.4.0

### ISSUE THREAD

**Issue by alebcay** [libofx/libofx#57]
Hello 👋 in the process of packaging libofx 0.10.4 for [Homebrew](https://brew.sh), we found that the compilation is failing with the following error:

```
libtool: compile:  g++-5 -DHAVE_CONFIG_H -I. -I.. -I. -I../inc -I/home/linuxbrew/.linuxbrew/opt/open-sp/include/OpenSP -DMAKEFILE_DTD_PATH=\"/home/linuxbrew/.linuxbrew/Cellar/libofx/0.10.4/share/libofx/dtd\" -DIN_LIBOFX -fvisibility=hidden -fvisibility-inlines-hidden -fvisibility=hidden -g -O2 -c ofx_preproc.cpp -o ofx_preproc.o >/dev/null 2>&1
In file included from ofx_containers.hh:24:0,
                 from ofx_container_security.cpp:27:
tree.hh:138:13: error: ‘ptrdiff_t’ does not name a type
     typedef ptrdiff_t                       difference_type;
             ^
Makefile:556: recipe for target 'ofx_container_security.lo' failed
make[1]: *** [ofx_container_security.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
```

We managed to work around the failure by adding `#include <cstddef>` into `tree.hh`. It's not clear to me exactly which platforms/environments may need this addition.

FYI the downstream issue at Homebrew is https://github.com/Homebrew/homebrew-core/pull/99546. Thanks!

**Comment by jralls** [comment]
`#include <cstddef>` is the [correct fix](https://en.cppreference.com/w/cpp/types/ptrdiff_t) (note the `#include` right under the title).

**Comment by cstim** [comment]
Committed, and tagged as 0.10.5. Have fun!

**Comment by alebcay** [comment]
Confirmed that previously failing build is now passing, appreciate the fast turnaround on this!
