### ISSUE TITLE
ofxconnect -b fails due to outdated URLs (moneycentral.msn.com)

### ISSUE THREAD

**Issue by clarete** [libofx/libofx#6]
Hi,

I was trying out `ofxconnect` today and I stumbled upon an error that seems to be caused by outdated URLs in the code.

Here's the exception:
```
master ♡ ofxconnect $ ./ofxconnect -b
ofx-bank-index.xml:2: parser error : Extra content at the end of the document
<body><h1>Object Moved</h1>This document may be found <a HREF="http://www.msn.co
^
terminate called after throwing an instance of 'xmlpp::parse_error'
  what():  Document not well-formed.
File ofx-bank-index.xml, line 2, column 1 (fatal):
Extra content at the end of the document
```

I'll look around and see if I find anything helpful! Thanks a lot for the library!

(also reported here: https://bugs.launchpad.net/ubuntu/+source/libofx/+bug/1168715)

**Comment by zacharyno** [comment]
Did you make any progress here or end up working around this?
