### ISSUE TITLE
"MainContainer is NULL trying to add element" errors

### ISSUE THREAD

**Issue by wrobelda** [libofx/libofx#62]
This is unrelated to #60. Our current KMyMoney build fails to import any OFX, including ANSI-encoded (1252 code page) ones. 

Errors are:

```
process data
LibOFX ERROR: MainContainer is NULL trying to add element F_
(Above message occurred on Line 11, Column 7)
LibOFX ERROR: MainContainer is NULL trying to add element SQ��
(Above message occurred on Line 14, Column 5)
LibOFX ERROR: MainContainer is NULL trying to add element SOGV�_�SCI��_
(Above message occurred on Line 15, Column 3)
LibOFX ERROR: MainContainer is NULL trying to add element BAF_P_h�_�_
(Above message occurred on Line 24, Column 9)
LibOFX ERROR: MainContainer is NULL trying to add element IRMc�N
(Above message occurred on Line 27, Column 9)
LibOFX ERROR: MainContainer is NULL trying to add element SRS}
(Above message occurred on Line 28, Column 7)
LibOFX ERROR: MainContainer is NULL trying to add element STQe�I
(Above message occurred on Line 29, Column 5)
LibOFX ERROR: MainContainer is NULL trying to add element BMRL�CSSW
(Above message occurred on Line 30, Column 3)
LibOFX ERROR: MainContainer is NULL trying to add element ON�
(Above message occurred on Line 31, Column 1)
process data done
```

Looks like somehow the data it attempts to import is gibberish, while the input file is a basic one from here: https://gist.github.com/jvz/2837829

This is on Windows, but I am testing if it's also affects other platforms. 

EDIT: tested and turns out it's Windows specific.

**Comment by wrobelda** [comment]
I tried debugging this with ofxdump, but the one that is built by kmymoney for Windows simply outputs nothing at all:

```
PS C:\Users\cromo\AppData\Local\KMyMoney> .\bin\ofxdump.exe --help
Usage: ofxdump [OPTION]... [FILE]...
ofxdump prints to stdout, in human readable form, everything the library
understands about a particular file or response, and sends errors to
stderr.  To know exactly what the library understands about of a particular
ofx response file, just call ofxdump on that file.

  -h, --help                  Print help and exit
  -V, --version               Print version and exit
  -f, --import-format=STRING  Force the file format of the file(s) specified
                                (default=`AUTODETECT')
      --list-import-formats   List available import file formats
                                'import-format' command
      --msg_parser            Output file parsing messages  (default=off)
      --msg_debug             Output messages meant for debugging
                                (default=off)
      --msg_warning           Output warning messages about abnormal conditions
                                and unknown constructs  (default=on)
      --msg_error             Output error messages  (default=on)
      --msg_info              Output informational messages about the progress
                                of the library  (default=on)
      --msg_status            Output status messages  (default=on)
PS C:\Users\cromo\AppData\Local\KMyMoney> .\bin\ofxdump.exe --msg_parser  Z:\Downloads\CHK_6549_CURRENT_VIEW.ofx
PS C:\Users\cromo\AppData\Local\KMyMoney> .\bin\ofxdump.exe --msg_parser -f ofx Z:\Downloads\CHK_6549_CURRENT_VIEW.ofx
PS C:\Users\cromo\AppData\Local\KMyMoney> .\bin\ofxdump.exe --msg_debug Z:\Downloads\CHK_6549_CURRENT_VIEW.ofx
PS C:\Users\cromo\AppData\Local\KMyMoney> .\bin\ofxdump.exe -V
ofxdump 0.10.5
```

The same file tested with ofxdump under macOS processes the file as expected. 

Feel free to download a copy of ofxdump in speech from https://binary-factory.kde.org/view/Windows%2064-bit/job/KMyMoney_Release_win64/

**Comment by wrobelda** [comment]
I bumped into a similar issue while working on #46 on macOS. While debugging, the `event.gi` that OpenSP returns is truncated to just one character, even though its length is as expected:
![Screen Shot 2022-07-06 at 12 33 49 PM](https://user-images.githubusercontent.com/1702435/177531314-1cf17a08-3d2b-4df5-8772-ae00da8ea9ca.png)

Once it gets `CharStringtostring`ed, the rest of the buffer is filled up with whatever platform/compiler comes up with. 

Now, it's unlikely that this is OpenSP's cause, since the same exact copy of library is used here by Homebrew to build `libofx` package, of which `ofxdump` executable works as expected.

EDIT: sample output on macOS:

```
/Users/cromo/Documents/Sourcecode/libofx/ofxdump/ofxdump --msg_parser /Users/cromo/Downloads/CHK_6549_CURRENT_VIEW.ofx
LibOFX INFO: libofx_proc_file(): File format not specified, autodetecting...
LibOFX INFO: libofx_proc_file(): Detected file format: OFX (Open Financial eXchange (OFX or QFX))
LibOFX STATUS: find_dtd():DTD found: ../dtd/opensp.dcl
LibOFX STATUS: find_dtd():DTD found: ../dtd/ofx160.dtd
LibOFX PARSER: startElement event received from OpenSP for element O
(Above message occurred on Line 1, Column 0)
LibOFX PARSER: StartElementEvent::element
(Above message occurred on Line 1, Column 1)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate O
(Above message occurred on Line 1, Column 1)
LibOFX PARSER: startElement event received from OpenSP for element SIGN
(Above message occurred on Line 1, Column 1)
LibOFX PARSER: StartElementEvent::element
(Above message occurred on Line 2, Column 1)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SIGN
```

**Comment by wrobelda** [comment]
I tested the same under Ubuntu 18.04 LTS with OpenSP installed from the repository and the and result is the same. I also tested it under Debian 5.10 and... it works fine.

**Comment by jralls** [comment]
That macOS output sure looks like `CharStringtostring` thinks `sizeof Char` is 1 but OpenSP thinks it's 4. That could happen if libofx is configured with `--with-no-opensp-multibyte` but OpenSP was built with SP_MULTI_BYTE defined.

Another (very unlikely) possibility is that the file is encoded in UTF32 and OpenSP is reading it as some single-byte encoding.

**Comment by wrobelda** [comment]
> libofx is configured with `--with-no-opensp-multibyte` but OpenSP was built with SP_MULTI_BYTE defined.

Thanks. That reminds me the FindOpenSP module should differentiate that. 

EDIT. Just realized it would be better handled by libofx itself through OpenSP's config.h. FAQ says:
```
Unfortunately, the auto-detection of this option was too fragile to release, because distros do not always distribute the config.h OpenSP was truly compiled with.  If the devel package for opensp was not compiled at the same time as the lib, it may give wrong value.
```
I think this goes against the grain and a good practice of relying on the deps' config.h? If a bistro doesn't distribute a correct `config.h`, then it's definitely something they should fix upstream, shouldn't they? And since there was no auto detection for a while now, we can safely assume all distros configure libofx with a correct `--with-no-opensp-multibyte` option, so adding the auto detection *back* but still having the switch take precedence can do no harm? 

EDIT: OK, never mind, the default assumes SP_MULTI_BYTE is on and `--with-no-opensp-multibyte` is optional, so unlikely that distros set it at all. Still, the original automake auto detection was reverted almost 20 years ago, so one would hope the quality of OpenSP package improved since.

**Comment by jralls** [comment]
> so one would hope the quality of OpenSP package improved since.

Seems optimistic. Debian packages are probably good since they're maintained by the same guy who did the last OpenSP release 20 years ago. I'd be a bit more skeptical of the less popular packaging systems like slackware and opensuse.

The [Homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libofx.rb) doesn't specify no-multibyte so maybe there's another way for it to get messed up.

**Comment by wrobelda** [comment]
Actually, two issues got mixed up. The macOS one was due to my cmake build not setting up the multibyte correctly. This is now fixed.

Windows, however, is still an issue: whether or not I set the SP_MULTI_BYTE, the output is garbled up. The OpenSP lib I am using is built with vcpkg, for which I provided a build recipe, and it's basically the same thing we use in kmymoney to build it on Windows, so most likely that's the cause. I'll keep this open for now but close as soon as I can confirm it.

**Comment by jralls** [comment]
What does `ofxdump --msg_parser` spit out on Windows?
I thought at first that the Windows output showed the opposite problem, that it was reading every fourth character, but that breaks down on line 15.

**Comment by jralls** [comment]
@wrobelda A thought: `(char)(((source.ptr)[i]))` depends on pointer arithmetic and a cast to get the right bytes out of the CharString. Maybe the assumptions that work with gcc and clang don't work with MSVS. Try breaking on `CharStringtostring` in the debugger and examining the variables.
