### ISSUE TITLE
Parse error with &copy; in <MEMO>

### ISSUE THREAD

**Issue by christopherlam** [libofx/libofx#72]
Sorry not sure if html &entities; should be allowable in ofx. Anyway an artificially planted `&copy;` in <MEMO> field is ignored. Attaching example.

[Data_export.txt](https://github.com/libofx/libofx/files/9382817/Data_export.txt)

```
$ ./ofxdump Data_export.ofx 
LibOFX INFO: libofx_proc_file(): File format not specified, autodetecting...
LibOFX INFO: libofx_proc_file(): Detected file format: OFX (Open Financial eXchange (OFX or QFX))
LibOFX STATUS: find_dtd():DTD found: ../dtd/opensp.dcl
LibOFX STATUS: find_dtd():DTD found: ../dtd/ofx160.dtd
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SIGNONMSGSRSV1
(Above message occurred on Line 2, Column 1)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SONRS
(Above message occurred on Line 3, Column 1)
ofx_proc_status():
    Ofx entity this status is relevant to: SONRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate BANKMSGSRSV1
(Above message occurred on Line 12, Column 1)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate STMTTRNRS
(Above message occurred on Line 13, Column 1)
ofx_proc_status():
    Ofx entity this status is relevant to: STMTTRNRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

LibOFX WARNING: OpenSP parser: warning (Not actually an error.):
/tmp/libofxtmp6xJunw:48:26:W: cannot generate system identifier for general entity "copy"

(Above message occurred on Line 48, Column 27)
LibOFX ERROR: OpenSP parser: otherError (misc parse error):
/tmp/libofxtmp6xJunw:48:26:E: general entity "copy" not defined and no default entity

(Above message occurred on Line 48, Column 27)
LibOFX ERROR: OpenSP parser: otherError (misc parse error):
/tmp/libofxtmp6xJunw:48:30:E: reference to entity "copy" for which no system identifier could be generated
/tmp/libofxtmp6xJunw:48:25: entity was defined here

(Above message occurred on Line 48, Column 31)
ofx_proc_account():
    Account ID: 123456  765432
    Account name: Bank account 765432
    Account type: CHECKING
    Default Currency: AUD
    Bank ID: 123456
    Account #: 765432
(snip)
```

**Comment by jralls** [comment]
No, as is standard in SGML only elements defined in the DTD are allowed. You can get a copy of the spec and DTD from https://financialdataexchange.org/FDX/About/OFX-Work-Group.aspx. You want the OFX 1.6 one. I see that the link is currently broken so I've attached a copy.
[OFX1.6.zip](https://github.com/libofx/libofx/files/9384289/OFX1.6.zip)

**Comment by christopherlam** [comment]
Ok looks like amp lt gt are the only allowable ones.
`&lt;` ==> `<`
Shouldn't the disallowed ones then simply pass through, i.e. escaped??

**Comment by jralls** [comment]
No, an OFX file is already formatted in SGML. It's the file creator's responsibility to correctly escape special characters.

**Comment by christopherlam** [comment]
NP

**Comment by christopherlam** [comment]
Still, a feature request: a mechanism to accumulate the errors/warnings during OFX processing so that they can be collected from the UI and displayable to the user.

**Comment by jralls** [comment]
The rule for SGML family parsers is that they are to terminate at the first parsing error. BTW, HTML and XML are flavors of SGML and work by the same rule.

Note as well that libofx shops out its SGML parsing to [OpenSP](http://openjade.sourceforge.net/doc/index.htm) that is no longer actively developed or maintained. Even if your request wasn't against the rules there's nobody to act on it.
