### ISSUE TITLE
missing version variables

### ISSUE THREAD

**Issue by genterminl** [libofx/libofx#76]
I just installed 0.10.6 on Gentoo, and then  tried to reinstall KMyMoney, which failed with 
In file included from /usr/include/qt5/QtCore/qiterator.h:43,
                 from /usr/include/qt5/QtCore/qmap.h:43,
                 from /usr/include/qt5/QtCore/QMap:1,
                 from /var/tmp/portage/app-office/kmymoney-9999/work/kmymoney-9999/kmymoney/interfaces/kmymoneyplugin.h:16,
                 from /var/tmp/portage/app-office/kmymoney-9999/work/kmymoney-9999/kmymoney/plugins/ofx/import/ofximporter.h:22,
                 from /var/tmp/portage/app-office/kmymoney-9999/work/kmymoney-9999/kmymoney/plugins/ofx/import/ofximporter.cpp:9:
/var/tmp/portage/app-office/kmymoney-9999/work/kmymoney-9999/kmymoney/plugins/ofx/import/ofximporter.cpp:381:5: error: operator '<<' has no left operand
  381 | #if QT_VERSION_CHECK(LIBOFX_MAJOR_VERSION, LIBOFX_MINOR_VERSION, LIBOFX_MICRO_VERSION) >= QT_VERSION_CHECK(0, 10, 0)

Poking into various files, I find the following in the libofx.h installed by 0.10.6

#define LIBOFX_MAJOR_VERSION 
#define LIBOFX_MINOR_VERSION 
#define LIBOFX_MICRO_VERSION 
#define LIBOFX_BUILD_VERSION 0

Shouldn't those contain the actual values?  (0, 10, and 6)  What I can't figure out is whether this is an issue in libofx itself, or in the Gentoo ebuild, so sorry if I've filed this in the wrong place.

**Comment by thesamesam** [comment]
Good spot. If in doubt, please do file a Gentoo bug, and we can always investigate and take it upstream if required.

https://github.com/libofx/libofx/commit/ef48375c4f9d0483c6992c292f2062c116154fcc and https://github.com/libofx/libofx/commit/f274a5b2e3bef7831faf13293f8aa7ab95df45e5 look relevant.

**Comment by thesamesam** [comment]
Thanks - submitted PR at https://github.com/libofx/libofx/pull/77 and fixed the issue in Gentoo.

**Comment by genterminl** [comment]
Thanks.  I confirm the Gentoo fixes work.  I'm still getting a crash in kmymoney, but that started before I upgraded libofx, and is certainly unrelated.

**Comment by cstim** [comment]
Out of curiosity: Why is this change in configure.ac needed to fix things in Gentoo? I can see that in configure.ac, the variable are declared as shell variables first, and only secondly in the AC_SUBST macro, but it has been this way since many years. Why does that introduce a bug in gentoo now but not earlier? Also, the two commits mentioned above change some of the macro ordering, but I can't see how they change the behaviour of the substitutions of those variables with respect to their substitution in inc/libofx.h.in?

Is there some autoconf behaviour in newer versions that wasn't there in older versions (such as 2.69 which I'm using when testing locally)?

**Comment by thesamesam** [comment]
I don't think it's Gentoo specific, actually (which is curious!)

If I grab libofx-0.10.6.tar.gz (the release tarball at https://github.com/libofx/libofx/releases/download/0.10.6/libofx-0.10.6.tar.gz), unpack it, then look at `inc/libofx.h`, I see:
```
[...]
#define LIBOFX_MAJOR_VERSION
#define LIBOFX_MINOR_VERSION
#define LIBOFX_MICRO_VERSION
#define LIBOFX_BUILD_VERSION 0
#define LIBOFX_VERSION_RELEASE_STRING ".."
[...]
```

This is without running `./configure` or in any way interacting with the files in the tarball.

(My guess for how the original issue got introduced recently is that AC_INIT might sanitise the environment when called, hence order affects it?)

EDIT: now that I think about it, ... should that even be in there? Doesn't configure generate that? But it's still wrong when I run autoreconf afterwards before the patch.
